name = "Scentsmp"
author = "ScentHarmony"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18914462876becf5723bca4a81b44fa2af8662c543ab80ae53af44f361dfb5ab"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
