name = "Scentsmp"
author = "ScentHarmony"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8940e931a6f774b6ccb3c6fb5e3199ca2983539e2f591d9fc405e8efbd81a5b5"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
