name = "Scentsmp"
author = "ScentHarmony"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b28e7207c8b0d4b1cbb80cac1596932e6ffba9552ca38c4c1c169677352acf1"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
